#!/bin/bash
# (c) by Robert Kalinowski <robert.kalinowski@sharkbits.com>

include bool
include error

#------------------------------------------------------------------------------
# Parse command line arguments
#
# Example:
#   while arg_parse "$@"; do
#     case "$op" in
#       -f|--foo)  arg_arg foo;;
#       --bar)     arg_optarg bar;;
#       -b|--baz)  arg_true baz;;
#       -*)        arg_error;;
#     esac
#   done
#
#   arg_arg db && echo "File is '$db'"  || error "No database"
#   while arg_arg; do
#     echo "Extra posistional argument '$arg'"
#   done
#
#
# Old example:
#   while arg_parse "$@"; do
#     case "$op" in
#       -f|--foo)  arg_arg; foo="$arg";;
#       --bar)     arg_optarg; bar="$optarg";;
#       -b|--baz)  baz="$TRUE";;
#     esac
#   done
#------------------------------------------------------------------------------
# Parse arguments
#
# arg_parse command-line-arguments...
#
# Function parse and set variables:
#  $op     - option
#  $arg    - option argument if any; variable is set after arg_arg call
#  $optarg - optional argument if any (--key=value); variable is set after arg_optarg call
#
#  Input:      $op:    $arg:  $optarg:
#  -f FOO      -f      FOO
#  -fFOO       -f      FOO    FOO
#  --foo FOO   --foo   FOO
#  --foo=FOO   --foo   FOO    FOO
#------------------------------------------------------------------------------
arg_parse()
{
	[[ -z "${_args_copied+x}" ]] && _args=("$@") && _args_copied=y && \
		_arg_end= && _arg_rest=()
	[[ ${#_args[@]} = 0 ]] && { unset _args_copied; return 1; }
	op="${_args[0]}"
	_args=("${_args[@]:1}")
	_arg_shift=
	_lnarg_shift=
	arg=
	optarg=
	if is_false "$_arg_end"; then
		case "$op" in
			--?*=*) _arg="${op#*=}";    _optarg="$_arg";   op="${op%%=*}";;
			--?*)   _arg="${_args[0]}"; _optarg="$TRUE";   _arg_shift=$TRUE;;
			--)     _arg_end=$TRUE; _arg_rest=("${_arg_rest[@]}" "${_args[@]}");
			        _args=(); return 1;;
			-??*)   _arg="${op:2}";     _optarg="${_arg}"; op="${op:0:2}";
			        _lnarg_shift=$TRUE; _args=("-$_arg" "${_args[@]}");;
			-?)     _arg="${_args[0]}"; _optarg=;          _arg_shift=$TRUE;;
			*)      _arg=;              _optarg=;          _arg_rest+=($op);;
		esac
	fi
}
#------------------------------------------------------------------------------
# Prepare arguments to next parsing
arg_reset()
{
	unset _args_copied
}
#------------------------------------------------------------------------------
# Return argument (optional or positional).
#
# arg_arg [var]
#
# If used in arg_parse loop, returns option argument. If Shift if neccesery.
# If used after arg_aprse loop, returns positional argument.
#------------------------------------------------------------------------------
arg_arg()
{
	if [[ ${#_args[@]} = 0 ]]; then
		[[ ${#_arg_rest[@]} = 0 ]] && arg= && return 1
		arg="${_arg_rest[0]}"
		_arg_rest=("${_arg_rest[@]:1}")
	else
		is_true "$_arg_shift" && _args=("${_args[@]:1}")
		if is_true "$_lnarg_shift"; then
			case "$op" in
				-[^-])  [[ $_arg ]] && _args=("${_args[@]:1}");;
			esac
			_lnarg_shift=
		fi
		_arg_shift=
		arg="$_arg"
	fi
	local re='^[a-zA-Z_]\w*$'
	[[ $1 =~ $re ]] && eval "$1='$arg'" || :
}
#------------------------------------------------------------------------------
# Return optional argument. Shift if neccesery.
#
# arg_optarg [var]
#------------------------------------------------------------------------------
arg_optarg()
{
	if is_true "$_lnarg_shift"; then
		case "$op" in
			-[^-])  [[ $_optarg ]] && _args=("${_args[@]:1}");;
		esac
		_lnarg_shift=
	fi
	arg="$_optarg"
	local re='^[a-zA-Z_]\w*$'
	[[ $1 =~ $re ]] && eval "$1='$arg'"
}
#------------------------------------------------------------------------------
# Return boolaen arguments (true).
#
# arg_true [var]
#------------------------------------------------------------------------------
arg_true()
{
	arg="$TRUE"
	local re='^[a-zA-Z_]\w*$'
	[[ $1 =~ $re ]] && eval "$1='$TRUE'"
}
#------------------------------------------------------------------------------
# Print unkown option error (default $op).
#
# arg_error [<argument_name>]
#------------------------------------------------------------------------------
arg_error()
{
	local a="${1:-${op:-$arg}}"
	error "Unknow argument '$op' in function '${FUNCNAME[1]}'" >&2
}
#------------------------------------------------------------------------------
