#!/bin/bash
# (c) by Robert Kalinowski <robert.kalinowski@sharkbits.com>


#------------------------------------------------------------------------------
TRUE='##TRUE##'
FALSE=''
#------------------------------------------------------------------------------
# true if not defined (like Python: val is None)
is_none()
{
	[[ -z ${1+_} ]]
}
#------------------------------------------------------------------------------
# true if is exactly true (like Python: val is True)
is_true()
{
	[[ $TRUE = $1 ]]
}
#------------------------------------------------------------------------------
# true if exactly false (like Python: val is False)
is_false()
{
	[[ $FALSE = $1 ]]
}
#------------------------------------------------------------------------------
# true if is like true (like Python: bool(val), where val is str)
if_true()
{
	case "$1" in
		''|[nN]*) false;;
		*)        true;;
	esac
}
#------------------------------------------------------------------------------
# true if is like false (line Python: not val, where val is str)
if_false()
{
	! if_true "$1"
}
#------------------------------------------------------------------------------
